version: "3.8"
services:
  app:
    image: python:3.9-slim-buster
  server:
    build: ./src/Server
    container_name: ransom-server
    hostname: server
    ports:
     - "5000:5000"
    privileged: true 
    restart: unless-stopped
